apiVersion: v2
name: tutorial-shop
description: A Helm chart for Tutorial Shop application
type: application
version: 0.1.1
appVersion: "1.0.1"
keywords:
  - shop
  - ecommerce
  - react
home: https://github.com/Kishinskiy/tutorial_shop
maintainers:
  - name: Tutorial Shop Team
